package com.kylentt.musicplayer.domain.musiclib.source.mediastore.query

import android.net.Uri
import com.kylentt.musicplayer.domain.musiclib.source.mediastore.BaseColumns


abstract class MediaStoreQuery internal constructor() {

	/**
	 * The Id, generated by [android.provider.MediaStore]
	 * @see [BaseColumns._ID]
	 */
	abstract val id: Long

	/**
	 * The Content Uri
	 */
	abstract val uri: Uri
}
