package com.flammky.android.medialib.providers.mediastore.base.media

import android.net.Uri

abstract class MediaStoreQuery internal constructor(
	/**
	 * The Id, generated by [android.provider.MediaStore]
	 * @see [BaseColumns._ID]
	 */
	val id: Long,

	/**
	 * The Content Uri
	 */
	val uri: Uri

	/* Generation ? */
)
