package com.kylentt.musicplayer.domain.musiclib.source.mediastore.base.media

import android.net.Uri
import android.provider.MediaStore

/**
 * [GoogleSource](https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-7.0.0_r36/core/java/android/provider/MediaStore.java)
 */

abstract class MediaStoreEntity {

	/**
	 * The id, generated by [MediaStore]
	 */
	abstract val id: Long

	/**
	 * The content [Uri], always in accordance with its [id]
	 */
	abstract val uri: Uri

	/**
	 * The Audio File Information.
	 */
	abstract val fileInfo: MediaStoreFile

	/**
	 * The Audio Metadata Information.
	 */
	abstract val metadata: MediaStoreMetadata
}
