package com.kylentt.musicplayer.medialib.android.provider.mediastore.base.media

import android.net.Uri

abstract class MediaStoreQuery internal constructor() {

	/**
	 * The Id, generated by [android.provider.MediaStore]
	 * @see [BaseColumns._ID]
	 */
	abstract val id: Long

	/**
	 * The Content Uri
	 */
	abstract val uri: Uri
}
