package com.kylentt.mediaplayer.ui.theme.md3
import androidx.compose.ui.graphics.Color

val Icon1 = Color(0xFFC5E3F6)
val Icon2 = Color(0xFFFC5C9C)

val BabyBlue = Color(0xFF89cff0)

val md_theme_light_primary = Color(0xFF00668a)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFc0e8ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001e2c)
val md_theme_light_secondary = Color(0xFF006685)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFbce9ff)
val md_theme_light_onSecondaryContainer = Color(0xFF001f2a)
val md_theme_light_tertiary = Color(0xFFb21e63)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd9e4)
val md_theme_light_onTertiaryContainer = Color(0xFF3e001c)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFFFBFE)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFE)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFF71d1ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF71d1ff)
val md_theme_dark_onPrimary = Color(0xFF003549)
val md_theme_dark_primaryContainer = Color(0xFF004c68)
val md_theme_dark_onPrimaryContainer = Color(0xFFc0e8ff)
val md_theme_dark_secondary = Color(0xFF65d3ff)
val md_theme_dark_onSecondary = Color(0xFF003547)
val md_theme_dark_secondaryContainer = Color(0xFF004d66)
val md_theme_dark_onSecondaryContainer = Color(0xFFbce9ff)
val md_theme_dark_tertiary = Color(0xFFffb0ca)
val md_theme_dark_onTertiary = Color(0xFF650032)
val md_theme_dark_tertiaryContainer = Color(0xFF8e0049)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd9e4)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
val md_theme_dark_inversePrimary = Color(0xFF00668a)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)