package com.flammky.mediaplayer.ui.activity.mainactivity.compose.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006685)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBEE9FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F2A)
val md_theme_light_secondary = Color(0xFF914C00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDCC3)
val md_theme_light_onSecondaryContainer = Color(0xFF2F1500)
val md_theme_light_tertiary = Color(0xFF186C32)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFA2F6AB)
val md_theme_light_onTertiaryContainer = Color(0xFF002109)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFE)
val md_theme_light_onBackground = Color(0xFF191C1E)
val md_theme_light_surface = Color(0xFFFBFCFE)
val md_theme_light_onSurface = Color(0xFF191C1E)
val md_theme_light_surfaceVariant = Color(0xFFDCE4E9)
val md_theme_light_onSurfaceVariant = Color(0xFF40484C)
val md_theme_light_outline = Color(0xFF70787D)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1F3)
val md_theme_light_inverseSurface = Color(0xFF2E3133)
val md_theme_light_inversePrimary = Color(0xFF6AD3FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006685)

val md_theme_dark_primary = Color(0xFF6AD3FF)
val md_theme_dark_onPrimary = Color(0xFF003546)
val md_theme_dark_primaryContainer = Color(0xFF004D65)
val md_theme_dark_onPrimaryContainer = Color(0xFFBEE9FF)
val md_theme_dark_secondary = Color(0xFFFFB77F)
val md_theme_dark_onSecondary = Color(0xFF4E2600)
val md_theme_dark_secondaryContainer = Color(0xFF6E3900)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCC3)
val md_theme_dark_tertiary = Color(0xFF87D991)
val md_theme_dark_onTertiary = Color(0xFF003914)
val md_theme_dark_tertiaryContainer = Color(0xFF005320)
val md_theme_dark_onTertiaryContainer = Color(0xFFA2F6AB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1E)
val md_theme_dark_onBackground = Color(0xFFE1E2E5)
val md_theme_dark_surface = Color(0xFF191C1E)
val md_theme_dark_onSurface = Color(0xFFE1E2E5)
val md_theme_dark_surfaceVariant = Color(0xFF40484C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C8CD)
val md_theme_dark_outline = Color(0xFF8A9297)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val md_theme_dark_inverseSurface = Color(0xFFE1E2E5)
val md_theme_dark_inversePrimary = Color(0xFF006685)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF6AD3FF)




val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)
