package dev.dexsr.klio.base.theme.md3.uxsystem

const val MATERIAL3_INTERACTIVE_COMPONENT_MINIMUM_SIZE_DP = 48f

const val MATERIAL3_INTERACTIVE_COMPONENT_SURFACE_CONTENT_DISABLED_ALPHA = 0.38f

const val MATERIAL3_INTERACTIVE_COMPONENT_SURFACE_DISABLED_ALPHA = 0.12f

const val MATERIAL3_INTERACTIVE_TEXT_COMPONENT_SURFACE_CONTENT_DISABLED_ALPHA = 0.68f

const val MATERIAL3_INTERACTIVE_TEXT_COMPONENT_SURFACE_DISABLED_ALPHA = 0.24f
